### ISSUE TITLE
Problems in learning

### ISSUE THREAD

**Issue by cyan-river** [afaber999/rust_breakout#1]
in `src/sprite_renderer.rs:66`

There are two glm::translate calls.
Running it with comments, I can see that both calls are indispensable.
I don't understand what is happening in these two calls, what is being implemented, can you explain for me?

**Comment by afaber999** [comment]
Hi, in order to rotate to object around its center, the center of the object has to be move first to the origin (first translate),  then the object can be rotated, after rotation the object will move back to its original position(in opposite direction of first translate) , therefore two translations are needed, hope this help

**Comment by cyan-river** [comment]
thinks for you The answer.
